[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

[build]
target = "x86_64-acadia-os.json"

[alias]
test_pc = "test --target=x86_64-unknown-linux-gnu -Z build-std=std --lib"
