[package]
name = "testbed"
version = "0.1.0"
edition = "2021"

[dependencies]
mammoth = { path = "../../lib/mammoth" }
yellowstone-yunq = { path = "../../lib/yellowstone" }
yunq = { path = "../../lib/yunq" }
